[package]
authors = ["The Rust Project Developers"]
name = "unwind"
version = "0.0.0"
edition = "2018"
include = [
  '/libunwind/*',
]

[lib]
test = false
bench = false
doc = false

[dependencies]
core = { version = '1.0.0', optional = true, package = 'rustc-std-workspace-core' }
libc = { version = "0.2.79", default-features = false }
compiler_builtins = { version = "0.1.0", optional = true }
cfg-if = "0.1.8"

[build-dependencies]
cc = { version = "1.0.1" }

[features]
llvm-libunwind = []
rustc-dep-of-std = ['compiler_builtins', 'core', 'libc/rustc-dep-of-std']
